Feature/unit testing
ChrisBarker-NOAA/wave_utils pull request #1
Opened 2017-10-01 16:14 UTC by jhoepken

I've added more unit testing to ``test_waves.py``, provided some documentation and cleaned up along the way.

2017-10-01 22:31 UTC, ChrisBarker-NOAA commented
Thanks for your interest in wave_utils!

I'll comment on the specific changes inline.

2017-10-01 22:39 UTC, ChrisBarker-NOAA requested changes
this looks great, thanks!

With a little cleanup (np.isclose -- or allclose()) I'll merge.

2017-10-01 22:39 UTC, ChrisBarker-NOAA commented on wave_utils/tests/test_waves.py
> +    assert abs(4.59043034 - waves.frequency(waves.g, 3.0, 0.3)) < 1e-7
we should use np.isclose() for these tests.

2017-10-01 22:39 UTC, ChrisBarker-NOAA commented on wave_utils/tests/test_waves.py
> +    assert np.isnan(waves.frequency(waves.g, -3.0, 0.3)) == 0
a bit better as:

`assert not np.isnan(waves.frequency(waves.g, -3.0, 0.3))`

2017-10-01 22:39 UTC, ChrisBarker-NOAA commented on wave_utils/tests/test_waves.py
> +    assert abs(1.199678640 - waves.dispersion(1.0)) < 1e-7
np.isclose() again...

2017-10-01 22:39 UTC, ChrisBarker-NOAA commented on wave_utils/tests/test_waves.py
> +    k = waves.wave_number(waves.g, omega, h)   # short waves
yes, this is better -- thanks!

2017-10-01 22:39 UTC, ChrisBarker-NOAA commented on wave_utils/waves.py
> -# if __name__ == "__main__":
yup -- time to get rid of all that :-)

2017-10-03 21:07 UTC, jhoepken commented
Hi Chris,
Thanks for the remarks. I'll apply and push changes tomorrow.

2017-10-04 08:08 UTC, jhoepken commented
Hi Chris,

I've applied the requested changes.

2017-10-09 23:22 UTC, ChrisBarker-NOAA commented on wave_utils/tests/test_waves.py
> +    assert np.isclose(4.59043034, waves.frequency(waves.g, 3.0, 0.3), atol=1e-7)
generally better to use the relative tolerance -- but these are all about the same magnitude, so this is OK.

2017-10-09 23:26 UTC, merged